keys:
  - &me age1n62xyamp34k22yefjgv4v375rran2zxs967a7lv53qdw8ks3wclsph385c
  - &host_ftomi_nixos age16f2stz48nj5eh9ll98q3gxsua4prqucf6zvye3e0xd08xlkwl3tq8cmneh

creation_rules:
  - path_regex: hosts/ftomi-nixos/secrets\.yaml$
    key_groups:
      - age:
          - *me
          - *host_ftomi_nixos
